-- fsm-keystone schema snapshot
-- Source: JPA entity model at com.fsm.keystone.entity.* (Spring Boot 4.0.7 / Hibernate 7)
-- Target:  PostgreSQL 16
-- Normalization: lowercase keywords, constraint names stripped, statements sorted alphabetically.
--
-- Bootstrap: initially constructed from entity-class analysis.
-- To verify or regenerate against a live Testcontainers instance:
--   cd keystone-backend
--   mvn test -Dtest=SchemaSnapshotTest                          (verify)
--   mvn test -Dtest=SchemaSnapshotTest -Dschema.snapshot.update=true  (regenerate)
-- Then review the diff and commit this file.
alter table customers add unique (email);
alter table part_usage add foreign key (part_id) references parts (id);
alter table part_usage add foreign key (used_by_user_id) references users (id);
alter table part_usage add foreign key (work_order_id) references work_orders (id);
alter table parts add unique (part_number);
alter table sites add foreign key (customer_id) references customers (id);
alter table status_history add foreign key (changed_by_user_id) references users (id);
alter table status_history add foreign key (work_order_id) references work_orders (id);
alter table time_logs add foreign key (technician_id) references users (id);
alter table time_logs add foreign key (work_order_id) references work_orders (id);
alter table users add foreign key (customer_id) references customers (id);
alter table users add unique (email);
alter table work_orders add foreign key (assigned_technician_id) references users (id);
alter table work_orders add foreign key (created_by_user_id) references users (id);
alter table work_orders add foreign key (customer_id) references customers (id);
alter table work_orders add foreign key (site_id) references sites (id);
alter table work_orders add unique (work_order_number);
create table customers (id bigint generated by default as identity, name varchar(255) not null, email varchar(255), phone varchar(255), billing_address varchar(255), created_at timestamp(6), updated_at timestamp(6), primary key (id));
create table part_usage (id bigint generated by default as identity, quantity_used integer, unit_price_at_usage numeric(38, 2), total_cost numeric(38, 2), used_at timestamp(6), work_order_id bigint not null, part_id bigint not null, used_by_user_id bigint, primary key (id));
create table parts (id bigint generated by default as identity, part_name varchar(255) not null, part_number varchar(255) not null, description varchar(255), unit_price numeric(38, 2), stock_quantity integer, active boolean, primary key (id));
create table sites (id bigint generated by default as identity, site_name varchar(255) not null, address varchar(255), city varchar(255), state varchar(255), pincode varchar(255), latitude float(53), longitude float(53), contact_person varchar(255), contact_phone varchar(255), customer_id bigint not null, primary key (id));
create table status_history (id bigint generated by default as identity, old_status varchar(255), new_status varchar(255), comment varchar(255), changed_at timestamp(6), work_order_id bigint not null, changed_by_user_id bigint, primary key (id));
create table time_logs (id bigint generated by default as identity, start_time timestamp(6), end_time timestamp(6), hours_spent numeric(38, 2), work_description varchar(1000), work_order_id bigint not null, technician_id bigint not null, primary key (id));
create table users (id bigint generated by default as identity, full_name varchar(255) not null, email varchar(255) not null, password varchar(255) not null, phone varchar(255), role varchar(255) not null, active boolean, created_at timestamp(6), customer_id bigint, primary key (id));
create table work_orders (id bigint generated by default as identity, work_order_number varchar(255) not null, title varchar(255) not null, description varchar(2000), status varchar(255), priority varchar(255), scheduled_start timestamp(6), scheduled_end timestamp(6), actual_start timestamp(6), actual_end timestamp(6), created_at timestamp(6), updated_at timestamp(6), customer_id bigint not null, site_id bigint not null, created_by_user_id bigint, assigned_technician_id bigint, primary key (id));
