-- V1__initial_schema.sql
-- Authoritative baseline DDL for the eight FSM Keystone application tables.
--
-- Source: Hibernate 7 / Spring Boot 4.0.7 schema export reconciled against
--         every @Entity in com.fsm.keystone.entity.
-- Target: PostgreSQL 16
-- Generation: GenerationType.IDENTITY → bigint generated by default as identity
-- Enum storage: @Enumerated(EnumType.STRING) → varchar(255)
-- BigDecimal: no explicit @Column(precision/scale) → Hibernate default numeric(38,2)
-- Double: Java double / Double → float(53) (IEEE-754 double precision)
-- LocalDateTime: timestamp(6)
--
-- Constraint naming: pk_{table}, uq_{table}_{column}, fk_{table}_{column}
-- ON DELETE: RESTRICT by default; CASCADE where the owning entity declares
--            CascadeType.ALL with orphanRemoval (sites) or CascadeType.ALL on
--            a child collection whose lifecycle is fully owned by the parent
--            (status_history, time_logs, part_usage ← work_orders).
--
-- Orphan columns from pre-Flyway ddl-auto=update runs are catalogued in
-- db/migration/README.md and must be addressed in later expand-then-contract
-- migrations; they are NOT added here.

-- ── 1. customers ─────────────────────────────────────────────────────────────
-- No foreign keys; must be created first.
CREATE TABLE customers (
    id              bigint generated by default as identity,
    name            varchar(255) NOT NULL,
    email           varchar(255),
    phone           varchar(255),
    billing_address varchar(255),
    created_at      timestamp(6),
    updated_at      timestamp(6),
    CONSTRAINT pk_customers      PRIMARY KEY (id),
    CONSTRAINT uq_customers_email UNIQUE (email)
);

-- ── 2. parts ─────────────────────────────────────────────────────────────────
-- No foreign keys; independent catalog table.
CREATE TABLE parts (
    id             bigint generated by default as identity,
    part_name      varchar(255) NOT NULL,
    part_number    varchar(255) NOT NULL,
    description    varchar(255),
    unit_price     numeric(38,2),
    stock_quantity integer,
    active         boolean,
    CONSTRAINT pk_parts              PRIMARY KEY (id),
    CONSTRAINT uq_parts_part_number  UNIQUE (part_number)
);

-- ── 3. users ──────────────────────────────────────────────────────────────────
-- FK to customers (nullable: only CUSTOMER-role users have a customer_id).
CREATE TABLE users (
    id          bigint generated by default as identity,
    full_name   varchar(255) NOT NULL,
    email       varchar(255) NOT NULL,
    password    varchar(255) NOT NULL,
    phone       varchar(255),
    role        varchar(255) NOT NULL,
    active      boolean,
    created_at  timestamp(6),
    customer_id bigint,
    CONSTRAINT pk_users       PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    -- RESTRICT: a customer with linked user accounts cannot be deleted until
    --           the accounts are unlinked or deleted first.
    CONSTRAINT fk_users_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT
);

-- ── 4. sites ──────────────────────────────────────────────────────────────────
-- FK to customers (NOT NULL: every site belongs to a customer).
-- Customer.sites has cascade = CascadeType.ALL, orphanRemoval = true,
-- so deleting a customer via JPA removes all its sites; CASCADE mirrors that.
CREATE TABLE sites (
    id             bigint generated by default as identity,
    site_name      varchar(255) NOT NULL,
    address        varchar(255),
    city           varchar(255),
    state          varchar(255),
    pincode        varchar(255),
    latitude       float(53),
    longitude      float(53),
    contact_person varchar(255),
    contact_phone  varchar(255),
    customer_id    bigint NOT NULL,
    CONSTRAINT pk_sites         PRIMARY KEY (id),
    -- CASCADE: Customer owns Sites with orphanRemoval=true; a SQL-level delete
    --          of a customer row also removes all its site rows.
    CONSTRAINT fk_sites_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE
);

-- ── 5. work_orders ────────────────────────────────────────────────────────────
-- FKs to customers (NOT NULL), sites (NOT NULL), users × 2 (nullable).
CREATE TABLE work_orders (
    id                     bigint generated by default as identity,
    work_order_number      varchar(255)  NOT NULL,
    title                  varchar(255)  NOT NULL,
    description            varchar(2000),
    status                 varchar(255),
    priority               varchar(255),
    scheduled_start        timestamp(6),
    scheduled_end          timestamp(6),
    actual_start           timestamp(6),
    actual_end             timestamp(6),
    created_at             timestamp(6),
    updated_at             timestamp(6),
    customer_id            bigint NOT NULL,
    site_id                bigint NOT NULL,
    created_by_user_id     bigint,
    assigned_technician_id bigint,
    CONSTRAINT pk_work_orders                    PRIMARY KEY (id),
    CONSTRAINT uq_work_orders_work_order_number  UNIQUE (work_order_number),
    -- RESTRICT: deleting a customer with open work orders is blocked; close or
    --           reassign the work orders first.
    CONSTRAINT fk_work_orders_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
    -- RESTRICT: a site cannot be deleted while work orders reference it.
    CONSTRAINT fk_work_orders_site
        FOREIGN KEY (site_id) REFERENCES sites (id) ON DELETE RESTRICT,
    -- RESTRICT: the creating user record is retained even after account deletion.
    CONSTRAINT fk_work_orders_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    -- RESTRICT: the assigned technician record is retained even after account deletion.
    CONSTRAINT fk_work_orders_assigned_technician
        FOREIGN KEY (assigned_technician_id) REFERENCES users (id) ON DELETE RESTRICT
);

-- ── 6. status_history ────────────────────────────────────────────────────────
-- FKs to work_orders (NOT NULL), users (nullable).
-- WorkOrder.statusHistory has cascade = CascadeType.ALL; CASCADE mirrors that.
CREATE TABLE status_history (
    id                 bigint generated by default as identity,
    old_status         varchar(255),
    new_status         varchar(255),
    comment            varchar(255),
    changed_at         timestamp(6),
    work_order_id      bigint NOT NULL,
    changed_by_user_id bigint,
    CONSTRAINT pk_status_history PRIMARY KEY (id),
    -- CASCADE: status history is fully owned by its work order
    --          (WorkOrder.statusHistory cascade = CascadeType.ALL).
    CONSTRAINT fk_status_history_work_order
        FOREIGN KEY (work_order_id) REFERENCES work_orders (id) ON DELETE CASCADE,
    -- RESTRICT: audit records survive even if the user account is later deleted.
    CONSTRAINT fk_status_history_changed_by
        FOREIGN KEY (changed_by_user_id) REFERENCES users (id) ON DELETE RESTRICT
);

-- ── 7. time_logs ─────────────────────────────────────────────────────────────
-- FKs to work_orders (NOT NULL), users (NOT NULL).
-- WorkOrder.timeLogs has cascade = CascadeType.ALL; CASCADE mirrors that.
CREATE TABLE time_logs (
    id               bigint generated by default as identity,
    start_time       timestamp(6),
    end_time         timestamp(6),
    hours_spent      numeric(38,2),
    work_description varchar(1000),
    work_order_id    bigint NOT NULL,
    technician_id    bigint NOT NULL,
    CONSTRAINT pk_time_logs PRIMARY KEY (id),
    -- CASCADE: time logs are fully owned by their work order
    --          (WorkOrder.timeLogs cascade = CascadeType.ALL).
    CONSTRAINT fk_time_logs_work_order
        FOREIGN KEY (work_order_id) REFERENCES work_orders (id) ON DELETE CASCADE,
    -- RESTRICT: time log entries survive even if the technician account is deleted.
    CONSTRAINT fk_time_logs_technician
        FOREIGN KEY (technician_id) REFERENCES users (id) ON DELETE RESTRICT
);

-- ── 8. part_usage ─────────────────────────────────────────────────────────────
-- FKs to work_orders (NOT NULL), parts (NOT NULL), users (nullable).
-- WorkOrder.partUsages has cascade = CascadeType.ALL; CASCADE mirrors that.
CREATE TABLE part_usage (
    id                  bigint generated by default as identity,
    quantity_used       integer,
    unit_price_at_usage numeric(38,2),
    total_cost          numeric(38,2),
    used_at             timestamp(6),
    work_order_id       bigint NOT NULL,
    part_id             bigint NOT NULL,
    used_by_user_id     bigint,
    CONSTRAINT pk_part_usage PRIMARY KEY (id),
    -- CASCADE: part usage records are fully owned by their work order
    --          (WorkOrder.partUsages cascade = CascadeType.ALL).
    CONSTRAINT fk_part_usage_work_order
        FOREIGN KEY (work_order_id) REFERENCES work_orders (id) ON DELETE CASCADE,
    -- RESTRICT: usage records form an audit trail; deleting a part does not
    --           erase the historical record of its use.
    CONSTRAINT fk_part_usage_part
        FOREIGN KEY (part_id) REFERENCES parts (id) ON DELETE RESTRICT,
    -- RESTRICT: usage records survive even if the recording user account is deleted.
    CONSTRAINT fk_part_usage_used_by
        FOREIGN KEY (used_by_user_id) REFERENCES users (id) ON DELETE RESTRICT
);
