package com.fsm.keystone.arch;

import com.tngtech.archunit.core.domain.JavaClasses;
import com.tngtech.archunit.core.importer.ClassFileImporter;
import com.tngtech.archunit.core.importer.ImportOption;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.io.IOException;
import java.lang.reflect.Method;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * ArchUnit-driven endpoint authorization inventory.
 *
 * <p>Scans {@code com.fsm.keystone.controller} for every handler method, reads its
 * {@code @PreAuthorize} expression (or records NONE), writes a deterministic text report
 * to {@code target/endpoint-authorization-inventory.txt}, and asserts that the total
 * discovered endpoint count matches the documented baseline.</p>
 *
 * <p>This test produces evidence for the authorization epic; it does NOT yet fail on
 * missing annotations — that gate belongs to WO-011+.</p>
 */
@Tag("unit")
class EndpointAuthorizationInventoryTest {

    /** Documented endpoint total — update this constant if a controller handler is added or removed. */
    private static final int EXPECTED_ENDPOINT_COUNT = 35;
    private static final String CONTROLLER_PACKAGE = "com.fsm.keystone.controller";

    @Test
    void inventoryEndpointsAndWriteReport() throws IOException {
        // ArchUnit scans the production classpath; DO_NOT_INCLUDE_TESTS excludes test classes.
        JavaClasses controllerClasses = new ClassFileImporter()
                .withImportOption(ImportOption.Predefined.DO_NOT_INCLUDE_TESTS)
                .importPackages(CONTROLLER_PACKAGE);

        List<EndpointEntry> entries = new ArrayList<>();

        for (var javaClass : controllerClasses) {
            Class<?> clazz;
            try {
                clazz = Class.forName(javaClass.getFullName());
            } catch (ClassNotFoundException e) {
                continue;
            }

            if (clazz.getAnnotation(RestController.class) == null
                    && clazz.getAnnotation(Controller.class) == null) {
                continue;
            }

            String basePath = resolveBasePath(clazz);
            for (Method method : clazz.getDeclaredMethods()) {
                EndpointEntry entry = buildEntry(method, basePath, clazz.getSimpleName());
                if (entry != null) {
                    entries.add(entry);
                }
            }
        }

        entries.sort(Comparator.comparing(EndpointEntry::sortKey));

        writeReport(entries);

        assertEquals(EXPECTED_ENDPOINT_COUNT, entries.size(),
                buildMismatchMessage(entries));
    }

    private static void writeReport(List<EndpointEntry> entries) throws IOException {
        Files.createDirectories(Paths.get("target"));
        var reportPath = Paths.get("target/endpoint-authorization-inventory.txt");

        StringBuilder sb = new StringBuilder();
        sb.append("# Endpoint Authorization Inventory\n");
        sb.append("# Generated by com.fsm.keystone.arch.EndpointAuthorizationInventoryTest\n");
        sb.append(String.format("# Total endpoints discovered: %d%n", entries.size()));
        sb.append("#\n");
        sb.append(String.format("%-10s %-55s %-40s %s%n", "METHOD", "PATH", "CONTROLLER", "@PreAuthorize"));
        sb.append("-".repeat(150)).append("\n");
        for (EndpointEntry e : entries) {
            sb.append(String.format("%-10s %-55s %-40s %s%n",
                    e.httpMethod(), e.path(), e.controller(), e.preAuthorize()));
        }

        Files.writeString(reportPath, sb.toString(), StandardCharsets.UTF_8);
    }

    private static String buildMismatchMessage(List<EndpointEntry> entries) {
        String discovered = entries.stream()
                .map(e -> "  " + e.httpMethod() + " " + e.path())
                .collect(Collectors.joining("\n"));
        return String.format(
                "Endpoint count drift detected: expected %d but discovered %d.%n"
                + "A controller handler was added or removed.%n"
                + "Update EXPECTED_ENDPOINT_COUNT in EndpointAuthorizationInventoryTest "
                + "or fix the controller.%n"
                + "Discovered endpoints:%n%s",
                EXPECTED_ENDPOINT_COUNT, entries.size(), discovered);
    }

    private static String resolveBasePath(Class<?> clazz) {
        RequestMapping rm = clazz.getAnnotation(RequestMapping.class);
        if (rm != null && rm.value().length > 0) {
            return rm.value()[0];
        }
        return "";
    }

    private static EndpointEntry buildEntry(Method method, String basePath, String controllerName) {
        String httpMethod = null;
        String subPath = "";

        if (method.isAnnotationPresent(GetMapping.class)) {
            httpMethod = "GET";
            String[] paths = method.getAnnotation(GetMapping.class).value();
            subPath = paths.length > 0 ? paths[0] : "";
        } else if (method.isAnnotationPresent(PostMapping.class)) {
            httpMethod = "POST";
            String[] paths = method.getAnnotation(PostMapping.class).value();
            subPath = paths.length > 0 ? paths[0] : "";
        } else if (method.isAnnotationPresent(PutMapping.class)) {
            httpMethod = "PUT";
            String[] paths = method.getAnnotation(PutMapping.class).value();
            subPath = paths.length > 0 ? paths[0] : "";
        } else if (method.isAnnotationPresent(PatchMapping.class)) {
            httpMethod = "PATCH";
            String[] paths = method.getAnnotation(PatchMapping.class).value();
            subPath = paths.length > 0 ? paths[0] : "";
        } else if (method.isAnnotationPresent(DeleteMapping.class)) {
            httpMethod = "DELETE";
            String[] paths = method.getAnnotation(DeleteMapping.class).value();
            subPath = paths.length > 0 ? paths[0] : "";
        } else if (method.isAnnotationPresent(RequestMapping.class)) {
            RequestMapping rm = method.getAnnotation(RequestMapping.class);
            if (rm.method().length > 0) {
                httpMethod = rm.method()[0].name();
                subPath = rm.value().length > 0 ? rm.value()[0] : "";
            }
        }

        if (httpMethod == null) {
            return null;
        }

        String fullPath;
        if (subPath.isEmpty()) {
            fullPath = basePath;
        } else if (subPath.startsWith("/")) {
            fullPath = basePath + subPath;
        } else {
            fullPath = basePath + "/" + subPath;
        }

        String preAuth = "NONE";
        PreAuthorize pa = method.getAnnotation(PreAuthorize.class);
        if (pa != null) {
            preAuth = pa.value();
        }

        return new EndpointEntry(controllerName, httpMethod, fullPath, preAuth);
    }

    private record EndpointEntry(String controller, String httpMethod, String path, String preAuthorize) {
        String sortKey() {
            return controller + ":" + httpMethod + ":" + path;
        }
    }
}
