package com.fsm.keystone.schema;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.MigrationInfo;
import org.flywaydb.core.api.MigrationState;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration test verifying the Flyway baseline behaviour for legacy databases.
 *
 * <p>Simulates an environment that already contains the application tables (created
 * before Flyway was introduced) by executing V1 SQL directly via JDBC without going
 * through Flyway. Then runs Flyway with {@code baselineOnMigrate=true} and
 * {@code baselineVersion=1} — the production flag for existing databases — and asserts
 * that V1 is recorded as baselined in {@code flyway_schema_history} rather than applied,
 * and that the pre-existing data is left intact.</p>
 *
 * <p>This test uses a manual (non-Spring) Flyway instance to decouple the baseline
 * verification from the application context lifecycle, which allows pre-populating the
 * database before Flyway sees it.</p>
 */
@Tag("integration")
@Testcontainers
class FlywayBaselineIT {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16");

    @Test
    void baseline_preExistingTables_recordedAsBaselinedWithoutApplyingV1() throws Exception {
        String jdbcUrl  = postgres.getJdbcUrl();
        String username = postgres.getUsername();
        String password = postgres.getPassword();

        // ── Step 1: Pre-create legacy schema and data directly via JDBC ────────
        // This simulates an environment that existed before Flyway was introduced.
        try (Connection conn = DriverManager.getConnection(jdbcUrl, username, password);
             Statement stmt = conn.createStatement()) {

            // Create tables in FK-safe order (mirrors the V1 migration)
            stmt.execute(
                "CREATE TABLE customers (" +
                "    id bigint generated by default as identity, " +
                "    name varchar(255) NOT NULL, " +
                "    email varchar(255), " +
                "    phone varchar(255), " +
                "    billing_address varchar(255), " +
                "    created_at timestamp(6), " +
                "    updated_at timestamp(6), " +
                "    PRIMARY KEY (id))");

            stmt.execute(
                "CREATE TABLE parts (" +
                "    id bigint generated by default as identity, " +
                "    part_name varchar(255) NOT NULL, " +
                "    part_number varchar(255) NOT NULL, " +
                "    description varchar(255), " +
                "    unit_price numeric(38,2), " +
                "    stock_quantity integer, " +
                "    active boolean, " +
                "    PRIMARY KEY (id))");

            stmt.execute(
                "CREATE TABLE users (" +
                "    id bigint generated by default as identity, " +
                "    full_name varchar(255) NOT NULL, " +
                "    email varchar(255) NOT NULL, " +
                "    password varchar(255) NOT NULL, " +
                "    phone varchar(255), " +
                "    role varchar(255) NOT NULL, " +
                "    active boolean, " +
                "    created_at timestamp(6), " +
                "    customer_id bigint, " +
                "    PRIMARY KEY (id))");

            // Insert a legacy row to confirm data is preserved after baseline
            stmt.execute(
                "INSERT INTO customers (name, email, created_at, updated_at) " +
                "VALUES ('Legacy Corp', 'legacy@example.test', NOW(), NOW())");
        }

        // Verify legacy row exists
        long legacyRowCount = countRows(jdbcUrl, username, password, "customers");
        assertThat(legacyRowCount).isEqualTo(1L);

        // ── Step 2: Run Flyway with baseline-on-migrate=true ──────────────────
        // Flyway detects existing tables (no flyway_schema_history), creates the
        // history table, inserts a BASELINE record for V1, and does NOT apply V1.
        Flyway flyway = Flyway.configure()
                .dataSource(jdbcUrl, username, password)
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("1")
                .cleanDisabled(true)
                .validateOnMigrate(false) // skip validation on fresh baseline run
                .load();

        flyway.migrate();

        // ── Step 3: Assert V1 is baselined, not applied ───────────────────────
        MigrationInfo[] applied = flyway.info().applied();
        assertThat(applied).isNotEmpty();

        MigrationInfo v1 = java.util.Arrays.stream(applied)
                .filter(m -> "1".equals(m.getVersion() != null ? m.getVersion().getVersion() : null))
                .findFirst()
                .orElseThrow(() -> new AssertionError("V1 not found in flyway_schema_history"));

        assertThat(v1.getState())
                .as("V1 must be BASELINE, not APPLIED")
                .isEqualTo(MigrationState.BASELINE);

        // ── Step 4: Assert legacy data is intact ──────────────────────────────
        long postBaselineRowCount = countRows(jdbcUrl, username, password, "customers");
        assertThat(postBaselineRowCount)
                .as("customers row count must be unchanged after baseline")
                .isEqualTo(legacyRowCount);
    }

    @Test
    void freshDatabase_appliesV1_notBaselined() throws Exception {
        // A second container is needed for a completely independent fresh DB.
        // We create a second container to avoid state from the baseline test.
        try (PostgreSQLContainer<?> freshDb = new PostgreSQLContainer<>("postgres:16")) {
            freshDb.start();

            Flyway flyway = Flyway.configure()
                    .dataSource(freshDb.getJdbcUrl(), freshDb.getUsername(), freshDb.getPassword())
                    .locations("classpath:db/migration")
                    .baselineOnMigrate(false)
                    .cleanDisabled(true)
                    .validateOnMigrate(true)
                    .load();

            flyway.migrate();

            MigrationInfo[] applied = flyway.info().applied();
            assertThat(applied).hasSize(1);
            assertThat(applied[0].getState())
                    .as("V1 must be SUCCESS on a fresh database, not BASELINE")
                    .isEqualTo(MigrationState.SUCCESS);

            // Verify all 8 tables were created
            try (Connection conn = DriverManager.getConnection(
                    freshDb.getJdbcUrl(), freshDb.getUsername(), freshDb.getPassword())) {
                for (String table : new String[]{"customers","parts","users","sites",
                        "work_orders","status_history","time_logs","part_usage"}) {
                    try (ResultSet rs = conn.getMetaData().getTables(
                            null, null, table, new String[]{"TABLE"})) {
                        assertThat(rs.next()).as("Table %s must exist after V1", table).isTrue();
                    }
                }
            }
        }
    }

    private long countRows(String url, String user, String pass, String table) throws Exception {
        try (Connection conn = DriverManager.getConnection(url, user, pass);
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM " + table)) {
            rs.next();
            return rs.getLong(1);
        }
    }
}
