-- Development seed data for FSM Keystone
-- Safe to run against a local dev database (profile: dev).
-- DO NOT execute in production.
--
-- Idempotent: uses INSERT ... ON CONFLICT DO NOTHING throughout.
-- Run with:
--   docker compose exec postgres-db psql -U postgres -d fsmdb -f /seed/seed-dev-data.sql
-- Or from the host (after copying the file into the container):
--   cat scripts/seed/seed-dev-data.sql | docker compose exec -T postgres-db psql -U postgres -d fsmdb

-- ============================================================
-- Customers
-- ============================================================
INSERT INTO customer (id, name, phone, email, address)
VALUES
  (1, 'Acme Corporation',      '555-0100', 'contact@acme.example.com',     '1 Industrial Way, Springfield'),
  (2, 'Globex Industries',     '555-0200', 'admin@globex.example.com',     '42 Reactor Road, Shelbyville'),
  (3, 'Initech Solutions',     '555-0300', 'info@initech.example.com',     '101 TPS Report Blvd, Austin'),
  (4, 'Umbrella Services Ltd', '555-0400', 'services@umbrella.example.com','7 Arklay Drive, Raccoon City')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- Sites (service locations belonging to customers)
-- ============================================================
INSERT INTO site (id, customer_id, name, address, contact_phone)
VALUES
  (1, 1, 'Acme - Main Factory',         '1 Industrial Way, Springfield',     '555-0101'),
  (2, 1, 'Acme - Warehouse B',          '9 Storage Lane, Springfield',       '555-0102'),
  (3, 2, 'Globex - Reactor Control',    '42 Reactor Road, Shelbyville',      '555-0201'),
  (4, 3, 'Initech - HQ Office',         '101 TPS Report Blvd, Austin',       '555-0301'),
  (5, 4, 'Umbrella - Research Lab',     '7 Arklay Drive, Raccoon City',      '555-0401')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- Users
-- Password hash below is a placeholder; the real hash must be
-- generated by the application's PasswordEncoder at runtime.
-- To create usable dev credentials, run the app with the dev
-- profile and use the /api/users POST endpoint, or run the
-- bootstrap-secrets script.
-- ============================================================
INSERT INTO app_user (id, email, full_name, role, customer_id, password_hash)
VALUES
  -- MANAGER (no customer association — sees all tenants)
  (1, 'manager@fsm.example.com',    'Alex Manager',     'MANAGER',  NULL, '$2a$10$PLACEHOLDER_HASH_DO_NOT_USE'),
  -- TECHNICIAN (no customer association — assigned to work orders, not to customers)
  (2, 'tech.jane@fsm.example.com',  'Jane Technician',  'TECHNICIAN', NULL, '$2a$10$PLACEHOLDER_HASH_DO_NOT_USE'),
  (3, 'tech.bob@fsm.example.com',   'Bob Technician',   'TECHNICIAN', NULL, '$2a$10$PLACEHOLDER_HASH_DO_NOT_USE'),
  -- CUSTOMER users (associated to a specific customer)
  (4, 'alice@acme.example.com',     'Alice Smith',      'CUSTOMER', 1, '$2a$10$PLACEHOLDER_HASH_DO_NOT_USE'),
  (5, 'charlie@globex.example.com', 'Charlie Burns',    'CUSTOMER', 2, '$2a$10$PLACEHOLDER_HASH_DO_NOT_USE'),
  (6, 'diana@initech.example.com',  'Diana Bolton',     'CUSTOMER', 3, '$2a$10$PLACEHOLDER_HASH_DO_NOT_USE')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- Parts
-- ============================================================
INSERT INTO part (id, name, part_number, unit_price, quantity_in_stock)
VALUES
  (1, 'HVAC Filter 16x20',          'HVF-16-20',  12.50, 200),
  (2, 'Circuit Breaker 20A',        'CB-20A',     45.00,  75),
  (3, 'Pump Seal Kit',              'PSK-001',    28.75,  50),
  (4, 'Conveyor Belt Splice Kit',   'CBS-KIT',    89.99,  30),
  (5, 'LED Panel Light 2x4',        'LED-2X4',   110.00,  40),
  (6, 'Hydraulic Fluid 5L',         'HF-5L',      22.00, 120),
  (7, 'Motor Brushes (set of 4)',   'MB-SET4',    15.50,  90),
  (8, 'Control Board — Model 3B',   'CTL-3B',    325.00,  10)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- Work Orders
-- ============================================================
INSERT INTO work_order (id, customer_id, site_id, assigned_technician_id, title, description, status, priority, scheduled_date, created_by)
VALUES
  -- Open work orders
  (1, 1, 1, 2, 'Annual HVAC Inspection',
      'Inspect and replace filters in all three HVAC units. Check refrigerant levels.',
      'OPEN', 'MEDIUM', '2026-08-15', 1),
  (2, 2, 3, 3, 'Reactor Coolant Pump Seal Replacement',
      'Replace primary seal kit on coolant pump unit CU-07. Full pressure test after replacement.',
      'IN_PROGRESS', 'HIGH', '2026-08-11', 1),
  (3, 3, 4, 2, 'Office Lighting Retrofit',
      'Replace 12 fluorescent panels with LED-2X4 units in the open-plan office.',
      'OPEN', 'LOW', '2026-08-20', 1),
  -- Completed work orders
  (4, 1, 2, 3, 'Conveyor Belt Splice Repair',
      'Emergency splice on belt section B7. Belt snapped during morning shift.',
      'COMPLETED', 'URGENT', '2026-08-05', 1),
  (5, 4, 5, 2, 'Control Board Replacement — Lab Incubator',
      'Replace faulty CTL-3B board in incubator unit INC-004. Calibrate after replacement.',
      'COMPLETED', 'HIGH', '2026-08-07', 1),
  -- Scheduled future work order
  (6, 2, 3, NULL, 'Annual Generator Service',
      'Full service on backup generator G-01: oil, filters, load test.',
      'OPEN', 'MEDIUM', '2026-09-01', 1)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- Part Usage (parts consumed on completed work orders)
-- ============================================================
INSERT INTO part_usage (id, work_order_id, part_id, quantity_used, notes)
VALUES
  -- WO-4: Conveyor Belt Splice Repair
  (1, 4, 4, 2, 'Used two splice kits for a double-splice repair'),
  -- WO-5: Control Board Replacement
  (2, 5, 8, 1, 'Replaced one CTL-3B control board'),
  -- WO-2: Coolant pump seal (in progress)
  (3, 2, 3, 1, 'Seal kit fitted; pressure test pending')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- Time Logs (labour time on work orders)
-- ============================================================
INSERT INTO time_log (id, work_order_id, technician_id, hours_worked, work_date, notes)
VALUES
  -- WO-4: Conveyor Belt Splice Repair
  (1, 4, 3, 3.5, '2026-08-05', 'Emergency call-out; splice and belt alignment'),
  -- WO-5: Control Board Replacement
  (2, 5, 2, 2.0, '2026-08-07', 'Board swap and calibration'),
  -- WO-2: Reactor Coolant Pump (in progress)
  (3, 2, 3, 1.5, '2026-08-11', 'Seal removal and preparation; pump down')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- Status History (audit trail for work order state changes)
-- ============================================================
INSERT INTO status_history (id, work_order_id, changed_by, old_status, new_status, changed_at, notes)
VALUES
  -- WO-4: OPEN → IN_PROGRESS → COMPLETED
  (1, 4, 1, 'OPEN',        'IN_PROGRESS', '2026-08-05 07:30:00+00', 'Emergency dispatch'),
  (2, 4, 3, 'IN_PROGRESS', 'COMPLETED',   '2026-08-05 11:15:00+00', 'Belt repaired and tested'),
  -- WO-5: OPEN → IN_PROGRESS → COMPLETED
  (3, 5, 1, 'OPEN',        'IN_PROGRESS', '2026-08-07 09:00:00+00', 'Technician on site'),
  (4, 5, 2, 'IN_PROGRESS', 'COMPLETED',   '2026-08-07 11:00:00+00', 'Board replaced; calibration complete'),
  -- WO-2: OPEN → IN_PROGRESS
  (5, 2, 1, 'OPEN',        'IN_PROGRESS', '2026-08-11 08:00:00+00', 'Technician on site; seal removal started')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- Sequence resets (after explicit ID inserts, reset sequences
-- so the application's auto-generated IDs do not collide)
-- ============================================================
SELECT setval('customer_id_seq',        (SELECT MAX(id) FROM customer),        true);
SELECT setval('site_id_seq',            (SELECT MAX(id) FROM site),            true);
SELECT setval('app_user_id_seq',        (SELECT MAX(id) FROM app_user),        true);
SELECT setval('part_id_seq',            (SELECT MAX(id) FROM part),            true);
SELECT setval('work_order_id_seq',      (SELECT MAX(id) FROM work_order),      true);
SELECT setval('part_usage_id_seq',      (SELECT MAX(id) FROM part_usage),      true);
SELECT setval('time_log_id_seq',        (SELECT MAX(id) FROM time_log),        true);
SELECT setval('status_history_id_seq',  (SELECT MAX(id) FROM status_history),  true);
